Update function for claiming airdrop
CarmineOptions/carmine-protocol pull request #148
Opened 2023-06-01 14:24 UTC by Chepelau

Update of `claim` function in `gov/airdrop.cairo` to account for second(and every other) aidrop. Should work if nothing was claimed in the first airdrop and also if it was. 

Function `get_eligible_amount` will be updated once the code for second airdrop is approved in airdrops repo.

2023-06-01 14:26 UTC, tensojka commented on contracts/governance/airdrop.cairo
> +        assert_nn(diff); // This should NOT happen
assert_nn_felt should be safer to use I believe

2023-06-01 14:27 UTC, tensojka requested changes

2023-06-01 14:30 UTC, MarekHauzr commented on contracts/governance/airdrop.cairo
> +    // was claimed
its hard to read the comment :/ to figure out what it means

2023-06-01 14:45 UTC, tensojka approved these changes

2023-06-02 12:33 UTC, MarekHauzr approved these changes

2023-06-02 14:19 UTC, merged